dataPath <- paste(dataRoot, drug, study, sep="/")
dataPath <- paste0(dataPath, "/")

author <- paste0("Author: ", Sys.getenv("LOGNAME"))

options(width=60)

titleString <- paste0("Autogenerated extreme value modelling report: ",
                      drug, ", Study ", study)

seed <- as.numeric(gsub("-", "", Sys.Date())) # no need to use date here
set.seed(seed)
